# Generated by Django 3.2.4 on 2021-08-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_userproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='name',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
